-- =============================================================================
-- Project: Ainuoyun Sales Assistant (SDXCX) ERP
-- Version: 1.0.0
-- Description: Init Database Schema based on database-design spec (BK-CI)
-- Date: 2026-03-31
-- =============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- 1. 基础资料 (Base Data)
-- ----------------------------

-- T_STORE: 门店信息
CREATE TABLE IF NOT EXISTS `T_STORE` (
  `STORE_ID` varchar(34) NOT NULL COMMENT '门店ID (S-32位UUID)',
  `STORE_NAME` varchar(128) NOT NULL COMMENT '门店名称',
  `DEALER_ID` varchar(64) DEFAULT NULL COMMENT '所属经销商/代理商ID',
  `ADDRESS` varchar(255) DEFAULT NULL COMMENT '详细地址',
  `CONTACT_PERSON` varchar(64) DEFAULT NULL COMMENT '联系人',
  `PHONE` varchar(32) DEFAULT NULL COMMENT '联系电话',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `DELETE_FLAG` bit(1) DEFAULT b'0' COMMENT '软删除标记',
  PRIMARY KEY (`STORE_ID`),
  KEY `IDX_DEALER_STORE` (`DEALER_ID`, `STORE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门店/经销商信息表';

-- T_USER: 用户/销售员
CREATE TABLE IF NOT EXISTS `T_USER` (
  `USER_ID` varchar(34) NOT NULL COMMENT '用户ID (U-32位UUID)',
  `USERNAME` varchar(64) NOT NULL COMMENT '登录账号',
  `NICKNAME` varchar(64) DEFAULT NULL COMMENT '显示名称',
  `PASSWORD_HASH` varchar(255) NOT NULL COMMENT '密码哈希',
  `ROLE` varchar(32) NOT NULL DEFAULT 'SALES' COMMENT '角色: SALES, MANAGER, BOSS, ADMIN',
  `STORE_ID` varchar(34) DEFAULT NULL COMMENT '所属门店ID',
  `LAST_LOGIN_TIME` timestamp NULL DEFAULT NULL COMMENT '最后登录时间',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `DELETE_FLAG` bit(1) DEFAULT b'0' COMMENT '状态标记 (0:正常, 1:停用)',
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `UNI_USERNAME` (`USERNAME`),
  KEY `IDX_STORE_USER` (`STORE_ID`, `ROLE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工/用户信息表';

-- T_CATEGORY: 商品类目
CREATE TABLE IF NOT EXISTS `T_CATEGORY` (
  `CATEGORY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CATEGORY_NAME` varchar(64) NOT NULL COMMENT '类目名称 (如：电脑, 手机)',
  `PARENT_ID` int(11) DEFAULT '0' COMMENT '上级类目ID',
  `LEVEL` tinyint(4) DEFAULT '1' COMMENT '层级',
  PRIMARY KEY (`CATEGORY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品类目表';

-- T_PRODUCT: 基础产品库
CREATE TABLE IF NOT EXISTS `T_PRODUCT` (
  `PN_CODE` varchar(64) NOT NULL COMMENT '商品PN码 (Part Number)',
  `PRODUCT_NAME` varchar(255) NOT NULL COMMENT '商品名称/型号',
  `BRAND_ID` varchar(64) DEFAULT NULL COMMENT '品牌标识',
  `CATEGORY_ID` int(11) DEFAULT NULL COMMENT '所属类目ID',
  `SPEC_DESC` mediumtext COMMENT '详细规格参数 (JSON)',
  `BASE_PRICE` decimal(12,2) DEFAULT '0.00' COMMENT '建议零售价',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `DELETE_FLAG` bit(1) DEFAULT b'0',
  PRIMARY KEY (`PN_CODE`),
  KEY `IDX_CATEGORY_PRODUCT` (`CATEGORY_ID`, `PRODUCT_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品主表';

-- T_SUPPLIER: 供应商
CREATE TABLE IF NOT EXISTS `T_SUPPLIER` (
  `SUPPLIER_ID` varchar(34) NOT NULL,
  `SUPPLIER_NAME` varchar(128) NOT NULL,
  `CONTACT_PERSON` varchar(64) DEFAULT NULL,
  `PHONE` varchar(32) DEFAULT NULL,
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`SUPPLIER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商信息表';


-- ----------------------------
-- 2. 采购与库存 (Procurement & Inventory)
-- ----------------------------

-- T_PURCHASE_ORDER: 采购单
CREATE TABLE IF NOT EXISTS `T_PURCHASE_ORDER` (
  `PO_ID` varchar(34) NOT NULL COMMENT '采购单号 (PO-UUID)',
  `SUPPLIER_ID` varchar(34) NOT NULL,
  `STORE_ID` varchar(34) NOT NULL,
  `TOTAL_AMOUNT` decimal(12,2) DEFAULT '0.00',
  `STATUS` tinyint(2) DEFAULT '0' COMMENT '0:草稿, 1:已入库',
  `CREATOR` varchar(34) DEFAULT NULL,
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PO_ID`),
  KEY `IDX_STORE_PO` (`STORE_ID`, `STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购订单主表';

-- T_PURCHASE_ITEM: 采购明细
CREATE TABLE IF NOT EXISTS `T_PURCHASE_ITEM` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PO_ID` varchar(34) NOT NULL,
  `PN_CODE` varchar(64) NOT NULL,
  `QUANTITY` int(11) DEFAULT '0',
  `UNIT_PRICE` decimal(12,2) DEFAULT '0.00',
  `RECEIVED_QTY` int(11) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `IDX_PO_PN` (`PO_ID`, `PN_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购明细表';

-- T_INVENTORY: 实时库存
CREATE TABLE IF NOT EXISTS `T_INVENTORY` (
  `STORE_ID` varchar(34) NOT NULL,
  `PN_CODE` varchar(64) NOT NULL,
  `QUANTITY` int(11) DEFAULT '0' COMMENT '实时库存数量',
  `LOW_STOCK_THRESHOLD` int(11) DEFAULT '5' COMMENT '低库存预警阈值',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`STORE_ID`, `PN_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='实时库存表';

-- T_STOCK_LOG: 出入库日志
CREATE TABLE IF NOT EXISTS `T_STOCK_LOG` (
  `LOG_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `STORE_ID` varchar(34) NOT NULL,
  `TYPE` varchar(32) NOT NULL COMMENT 'PURCHASE:采购入库, SALES:销售出库, TRANSFER:调拨, ADJUST:调整',
  `ORDER_REF_ID` varchar(64) DEFAULT NULL COMMENT '关联单号',
  `PN_CODE` varchar(64) NOT NULL,
  `QTY_CHANGE` int(11) NOT NULL COMMENT '变动数量 (正数为增, 负数为减)',
  `REMARK` varchar(255) DEFAULT NULL,
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`LOG_ID`),
  KEY `IDX_STORE_PN_TIME` (`STORE_ID`, `PN_CODE`, `CREATE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存变动记录表';

-- T_SN_POOL: 序列号/IMEI 追踪池
CREATE TABLE IF NOT EXISTS `T_SN_POOL` (
  `SN_CODE` varchar(128) NOT NULL COMMENT 'SN码或IMEI码',
  `PN_CODE` varchar(64) NOT NULL,
  `IMEI1` varchar(64) DEFAULT NULL,
  `IMEI2` varchar(64) DEFAULT NULL,
  `STATUS` tinyint(4) DEFAULT '1' COMMENT '1:在库, 2:已售, 3:退货待入库, 4:返修中, 5:坏件',
  `STORE_ID` varchar(34) DEFAULT NULL COMMENT '当前所在门店ID',
  `ORDER_ID` varchar(34) DEFAULT NULL COMMENT '关联销售订单ID',
  `IN_TIME` timestamp NULL DEFAULT NULL COMMENT '入库时间',
  `OUT_TIME` timestamp NULL DEFAULT NULL COMMENT '销售出库时间',
  `UPDATE_TIME` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`SN_CODE`),
  KEY `IDX_PN_SN` (`PN_CODE`, `STATUS`),
  KEY `IDX_STORE_SN` (`STORE_ID`, `STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品序列号追踪池';


-- ----------------------------
-- 3. 销售与财务 (Sales & Finance)
-- ----------------------------

-- T_ORDER: 销售订单
CREATE TABLE IF NOT EXISTS `T_ORDER` (
  `ORDER_ID` varchar(34) NOT NULL COMMENT '订单ID (ORD-UUID)',
  `STORE_ID` varchar(34) NOT NULL,
  `SALES_PERSON_ID` varchar(34) NOT NULL COMMENT '经办销售员ID',
  `CUSTOMER_NAME` varchar(64) DEFAULT NULL,
  `CUSTOMER_PHONE` varchar(32) DEFAULT NULL,
  `CUSTOMER_SOURCE` varchar(64) DEFAULT NULL COMMENT '客户来源 (如:自然进店)',
  `TOTAL_AMOUNT` decimal(12,2) DEFAULT '0.00' COMMENT '订单原价总计',
  `SUBSIDY_AMOUNT` decimal(12,2) DEFAULT '0.00' COMMENT '补贴总额 (国补+教育)',
  `FINAL_AMOUNT` decimal(12,2) DEFAULT '0.00' COMMENT '应收总额 (实付)',
  `STATUS` tinyint(2) DEFAULT '1' COMMENT '1:待收, 2:已付, 3:已取消',
  `REMARK` text,
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ORDER_ID`),
  KEY `IDX_STORE_ORDER_TIME` (`STORE_ID`, `STATUS`, `CREATE_TIME`),
  KEY `IDX_SALES_ORDER` (`SALES_PERSON_ID`, `CREATE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='销售订单主表';

-- T_ORDER_ITEM: 订单明细
CREATE TABLE IF NOT EXISTS `T_ORDER_ITEM` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORDER_ID` varchar(34) NOT NULL,
  `PN_CODE` varchar(64) NOT NULL,
  `SN_CODE` varchar(128) NOT NULL,
  `COST_PRICE` decimal(12,2) DEFAULT '0.00' COMMENT '采购进价 (用于核算利润)',
  `SELL_PRICE` decimal(12,2) DEFAULT '0.00' COMMENT '实际售价',
  `SUBSIDY_TYPE` varchar(32) DEFAULT NULL COMMENT 'NAT:国补, EDU:教育补',
  `SUBSIDY_VAL` decimal(12,2) DEFAULT '0.00' COMMENT '单品折算补贴金额',
  PRIMARY KEY (`ID`),
  KEY `IDX_ORDER_PN` (`ORDER_ID`, `PN_CODE`),
  UNIQUE KEY `UNI_ORDER_SN` (`ORDER_ID`, `SN_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单商品明细表';

-- T_PAYMENT: 支付明细
CREATE TABLE IF NOT EXISTS `T_PAYMENT` (
  `PAY_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORDER_ID` varchar(34) NOT NULL,
  `METHOD_ID` varchar(32) NOT NULL COMMENT '支付方式ID (CASH, ALIPAY, WECHAT等)',
  `AMOUNT` decimal(12,2) NOT NULL DEFAULT '0.00',
  `PAY_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PAY_ID`),
  KEY `IDX_ORDER_PAY` (`ORDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付流水记录表';

-- T_ORDER_PHOTO: 合规照片凭证
CREATE TABLE IF NOT EXISTS `T_ORDER_PHOTO` (
  `PHOTO_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORDER_ID` varchar(34) NOT NULL,
  `PHOTO_TYPE` varchar(32) NOT NULL COMMENT 'VOUCHER:补贴凭证, PRODUCT:实物图, OTHER:其他',
  `PHOTO_URL` varchar(512) NOT NULL COMMENT '本地文件路径',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PHOTO_ID`),
  KEY `IDX_ORDER_PHOTO` (`ORDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单凭证照片表';


-- ----------------------------
-- 4. 提成与分润 (Commission & Revenue Share)
-- ----------------------------

-- T_COMMISSION_RULE: 提成规则配置
CREATE TABLE IF NOT EXISTS `T_COMMISSION_RULE` (
  `RULE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CATEGORY_ID` int(11) DEFAULT NULL COMMENT '适用类目',
  `TYPE` varchar(32) NOT NULL COMMENT 'FIXED:固定金额, RATIO:比例, PROFIT:毛利分成',
  `VALUE` decimal(12,2) NOT NULL COMMENT '提成值',
  `REMARK` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`RULE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='销售提成规则表';

-- T_ORDER_SHARE: 业绩分成/提成明细
CREATE TABLE IF NOT EXISTS `T_ORDER_SHARE` (
  `SHARE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORDER_ID` varchar(34) NOT NULL,
  `USER_ID` varchar(34) NOT NULL COMMENT '获益销售员ID',
  `SHARE_AMOUNT` decimal(12,2) DEFAULT '0.00' COMMENT '分润/提成金额',
  `SHARE_TYPE` varchar(32) DEFAULT 'MAIN' COMMENT 'MAIN:主销, ASSIST:辅销',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`SHARE_ID`),
  KEY `IDX_USER_SHARE_TIME` (`USER_ID`, `CREATE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单提成记录表';


-- ----------------------------
-- 5. 扩展预留 (Reserved for Member & Service)
-- ----------------------------

-- T_MEMBER: 会员中心
CREATE TABLE IF NOT EXISTS `T_MEMBER` (
  `MEMBER_ID` varchar(34) NOT NULL,
  `PHONE` varchar(32) NOT NULL,
  `NAME` varchar(64) DEFAULT NULL,
  `POINTS` int(11) DEFAULT '0',
  `TOTAL_SPEND` decimal(12,2) DEFAULT '0.00',
  `LEVEL` tinyint(2) DEFAULT '1',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`MEMBER_ID`),
  UNIQUE KEY `UNI_PHONE` (`PHONE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员资料表';

-- T_SERVICE_ORDER: 售后维修单
CREATE TABLE IF NOT EXISTS `T_SERVICE_ORDER` (
  `SERVICE_ID` varchar(34) NOT NULL COMMENT 'SER-UUID',
  `SN_CODE` varchar(128) NOT NULL,
  `CUSTOMER_NAME` varchar(64) DEFAULT NULL,
  `PROBLEM_DESC` text,
  `REPAIR_STATUS` tinyint(2) DEFAULT '1' COMMENT '1:待检, 2:维修中, 3:已修复, 4:已返还',
  `ESTIMATED_COST` decimal(12,2) DEFAULT '0.00',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`SERVICE_ID`),
  KEY `IDX_SN_SERVICE` (`SN_CODE`, `REPAIR_STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='售后/维修单表';

-- T_WARRANTY: 保修追踪
CREATE TABLE IF NOT EXISTS `T_WARRANTY` (
  `SN_CODE` varchar(128) NOT NULL,
  `WARRANTY_START` date DEFAULT NULL,
  `WARRANTY_END` date DEFAULT NULL,
  `WARRANTY_TYPE` varchar(64) DEFAULT 'OFFICIAL' COMMENT 'OFFICIAL:原厂, STORE:延保',
  PRIMARY KEY (`SN_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='保修信息追踪表';

SET FOREIGN_KEY_CHECKS = 1;
